##########################
## Site Config Settings ##
##########################

# Theme version
version: 2.0.1

# Header
menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss

# Sidebar
widgets:
  - recent_posts
  - category
  - tag
  - archive
  #- weibo
  - links

# Toc
toc:
  enable: true
  number: false

# Static files
js: js
css: css

# Date_formats
date_formats:
  archive: "MM月DD日"
  category: "YYYY/MM/DD"
  post: "MMM DD, YYYY"
  tag: "YYYY/MM/DD"

# Extensions
Plugins:
  hexo-generator-feed
  hexo-generator-sitemap
  hexo-generator-baidu-sitemap

#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20

#sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

#Local search
## Use a javascript-based local search engine, true/false.
local_search: true

#Cmments
comment:
  duoshuo: #chaooo ## duoshuo_shortname
  disqus: ## disqus_shortname
  livere: ## 来必力(data-uid)
  uyan: ## 友言(uid)
  cloudTie: ## 网易云跟帖(productKey)
  changyan: ## 畅言需在下方配置两个参数，此处不填。
    appid: ## 畅言(appid)
    appkey: ##畅言(appkey)

#Share
baidu_share: true ## 百度分享
JiaThis_share: ##true ##JiaThis分享
duoshuo_share: #true ##true 多说分享必须和多说评论一起使用。
addToAny_share: # AddToAny share. Empty list hides. List items are service name at url. For ex: email for '<a href="https://www.addtoany.com/add_to/email?linkurl=...'
#  - twitter
#  - baidu
#  - facebook
#  - google_plus
#  - linkedin
#  - email

# Analytics
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42025684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 1006843030519956000

# Miscellaneous
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.

# About page
about:
  photo_url: https://xinxiamu.github.io/favicon.ico ## Your photo e.g. http://obzf7z93c.bkt.clouddn.com/themeauthor.jpg
  items:
  - label: email
    ## Your email with mailto: e.g.  mailto:zhenggchaoo@gmail.com
    url: https://mail.qq.com
    ## Your email e.g.  zhenggchaoo@gmail.com
    title: 932852117@qq.com
  - label: github
    url: ## Your github'url e.g.  https://github.com/chaooo
    title: ## Your github'name e.g.  chaooo
  - label: weibo
    url: ## Your weibo's url e.g.  http://weibo.com/zhengchaooo
    title: ## Your weibo's name e.g.  秋过冬漫长
# - label: twitter
#   url: 
#   title:
# - label: facebook
#   url:
#   title:

# Links widget. Empty links will hide widget.
links:
  - title: 程序员DD|翟永超的博客
    url: http://blog.didispace.com/
  - title: 泥瓦匠的博客
    url: http://www.bysocket.com/
  - title: 周立|Spring Cloud的博客
    url: http://itmuch.com/
  - title: 梁桂钊的博客
    url: http://itmuch.com/
  - title: 纯洁的微笑的博客
    url: http://www.ityouknow.com/
  - title: wier的博客
    url: https://my.oschina.net/u/1859679/blog
  - title: Any-Video
    url: http://www.ictgu.cn/
  - title: 在线作图
    url: https://www.processon.com/
  - title: spring4all
    url: http://spring4all.com/
  - title: 开源中国
    url: https://www.oschina.net/
  - title: w3cschool学习网
    url: https://www.w3cschool.cn/
  - title: angular中文教程
    url: https://angular.cn/
  - title: java教程
    url: http://tutorials.jenkov.com
  - title: programcreek-java教程
    url: https://www.programcreek.com/
  - title: howtodoinjava
    url: https://howtodoinjava.com/
  - title: javadoc(8/9)
    url: http://docs.oracle.com/javase/9/docs/api/
  - title: eugenp/tutorials
    url: https://github.com/eugenp/tutorials